#!/bin/bash

echo "🚀 API-Direct Subdomain Deployment Guide"
echo "========================================"
echo ""
echo "Since Vercel requires login, please run these commands manually:"
echo ""
echo "1️⃣  Deploy Console (console.apidirect.dev):"
echo "-------------------------------------------"
echo "cd web/console"
echo "vercel"
echo "# Choose: Set up and deploy"
echo "# Scope: Your account"
echo "# Link to existing? N"
echo "# Project name: apidirect-console"
echo "# Then go to Vercel dashboard → Settings → Domains → Add console.apidirect.dev"
echo ""
echo "2️⃣  Deploy Marketplace (marketplace.apidirect.dev):"
echo "------------------------------------------------"
echo "cd ../marketplace"
echo "npm install"  
echo "vercel"
echo "# Choose: Set up and deploy"
echo "# Scope: Your account" 
echo "# Link to existing? N"
echo "# Project name: apidirect-marketplace"
echo "# Framework: Next.js"
echo "# Then go to Vercel dashboard → Settings → Domains → Add marketplace.apidirect.dev"
echo ""
echo "3️⃣  Deploy Docs (docs.apidirect.dev) - Optional:"
echo "----------------------------------------------"
echo "cd ../docs"
echo "vercel"
echo "# Project name: apidirect-docs"
echo "# Add domain: docs.apidirect.dev"
echo ""
echo "4️⃣  For API Backend (api.apidirect.dev) - When Ready:"
echo "---------------------------------------------------"
echo "cd ../../backend"
echo "vercel"
echo "# Project name: apidirect-api"
echo "# Add domain: api.apidirect.dev"
echo ""
echo "📝 After each deployment:"
echo "- Go to vercel.com/dashboard"
echo "- Click on the project"
echo "- Settings → Domains"
echo "- Add the subdomain"
echo "- Wait 5-10 minutes for SSL"
echo ""
echo "✅ Your DNS records are already set up in Namecheap!"
echo ""