version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: apidirect
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: apidirect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apidirect"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage Service
  storage:
    build: ./services/storage
    ports:
      - "8087:8080"
    environment:
      PORT: 8080
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CODE_STORAGE_BUCKET: ${CODE_STORAGE_BUCKET:-api-direct-code-storage-dev}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
    depends_on:
      - postgres

  # Deployment Service
  deployment:
    build: ./services/deployment
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      KUBECONFIG: /root/.kube/config
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
    volumes:
      - ~/.kube:/root/.kube:ro
    depends_on:
      - postgres

  # API Key Management Service
  apikey:
    build: ./services/apikey
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
      DATABASE_URL: postgresql://apidirect:localpassword@postgres:5432/apidirect?sslmode=disable
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy

  # API Gateway Service
  gateway:
    build: ./services/gateway
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      REDIS_URL: redis://redis:6379
      API_KEY_SERVICE_URL: http://apikey:8083
      METERING_SERVICE_URL: http://metering:8084
      GIN_MODE: debug
    depends_on:
      - redis
      - apikey

  # Metering Service
  metering:
    build: ./services/metering
    ports:
      - "8084:8084"
    environment:
      PORT: 8084
      DATABASE_URL: postgresql://apidirect:localpassword@postgres:5432/apidirect?sslmode=disable
      REDIS_URL: redis://redis:6379
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Creator Portal
  creator-portal:
    build: ./web/creator-portal
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8082
      REACT_APP_COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      REACT_APP_COGNITO_CLIENT_ID: ${COGNITO_WEB_CLIENT_ID}
      REACT_APP_COGNITO_REGION: ${AWS_REGION:-us-east-1}
    volumes:
      - ./web/creator-portal:/app
      - /app/node_modules
    command: npm start

  # Billing Service
  billing:
    build: ./services/billing
    ports:
      - "8085:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://apidirect:localpassword@postgres:5432/apidirect?sslmode=disable
      REDIS_URL: redis://redis:6379
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_your_stripe_secret_key}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_your_webhook_secret}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      metering:
        condition: service_healthy
      apikey:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Marketplace Frontend
  marketplace:
    build: 
      context: ./web/marketplace
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8082}
      NEXT_PUBLIC_APIKEY_SERVICE_URL: ${NEXT_PUBLIC_APIKEY_SERVICE_URL:-http://localhost:8083}
      NEXT_PUBLIC_BILLING_SERVICE_URL: ${NEXT_PUBLIC_BILLING_SERVICE_URL:-http://localhost:8085}
      NEXT_PUBLIC_METERING_SERVICE_URL: ${NEXT_PUBLIC_METERING_SERVICE_URL:-http://localhost:8084}
      NEXT_PUBLIC_MARKETPLACE_SERVICE_URL: ${NEXT_PUBLIC_MARKETPLACE_SERVICE_URL:-http://localhost:8086}
      NEXT_PUBLIC_GATEWAY_URL: ${NEXT_PUBLIC_GATEWAY_URL:-http://localhost:8082}
      NEXT_PUBLIC_AWS_REGION: ${AWS_REGION:-us-east-1}
      NEXT_PUBLIC_AWS_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      NEXT_PUBLIC_AWS_USER_POOL_WEB_CLIENT_ID: ${COGNITO_WEB_CLIENT_ID}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-pk_test_51RTaKEIeLEFImVyF5u9rm8nDSN42hWmrNbxSLk16k2KBSiSlLPn2np3vljS9RnoJxAuKrrnqiYJqFGU7MIwSTZFT00idvU8gKF}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-development-secret}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3001}
      DATABASE_URL: postgresql://apidirect:localpassword@postgres:5432/apidirect?sslmode=disable
      REDIS_URL: redis://redis:6379
    volumes:
      # Only mount in development mode
      - ./web/marketplace:/app:${MOUNT_SOURCE:-ro}
      - marketplace_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Elasticsearch for advanced search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kibana for Elasticsearch management
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Marketplace API Service
  marketplace-api:
    build: ./services/marketplace
    ports:
      - "8086:8086"
    environment:
      PORT: 8086
      DATABASE_URL: postgresql://apidirect:localpassword@postgres:5432/apidirect?sslmode=disable
      ELASTICSEARCH_URL: http://elasticsearch:9200
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  marketplace_node_modules:
