apiVersion: v1
kind: Service
metadata:
  name: apikey-service
  namespace: api-direct
spec:
  selector:
    app: apikey
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikey
  namespace: api-direct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apikey
  template:
    metadata:
      labels:
        app: apikey
    spec:
      serviceAccountName: api-direct-service-account
      containers:
      - name: apikey
        image: api-direct-apikey:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: connection-string
        - name: GIN_MODE
          value: "release"
        - name: COGNITO_USER_POOL_ID
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: cognito_user_pool_id
        - name: COGNITO_REGION
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: aws_region
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: api-direct
type: Opaque
stringData:
  # This will be populated by the deployment script with actual RDS credentials
  connection-string: "postgresql://username:password@host:5432/apidirect?sslmode=require"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: api-direct
data:
  # These will be populated by Terraform outputs
  aws_region: "us-east-1"
  cognito_user_pool_id: "us-east-1_XXXXXXXXX"
  cognito_cli_client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  cognito_web_client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
