apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: api-platform
spec:
  selector:
    app: billing-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: api-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: billing-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-platform-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-platform-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: api-platform-secrets
              key: stripe-webhook-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-platform-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-service-network-policy
  namespace: api-platform
spec:
  podSelector:
    matchLabels:
      app: billing-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
    - podSelector:
        matchLabels:
          app: marketplace-frontend
    - podSelector:
        matchLabels:
          app: creator-portal
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: metering-service
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - podSelector:
        matchLabels:
          app: apikey-service
    ports:
    - protocol: TCP
      port: 8080
  # Allow external HTTPS for Stripe API
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
  namespace: api-platform
data:
  platform-commission-rate: "0.20"
  minimum-payout-amount: "50.00"
  payout-schedule: "monthly"
  supported-currencies: "USD"
  max-payment-methods: "5"
