apiVersion: apps/v1
kind: Deployment
metadata:
  name: payout-service
  namespace: api-direct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payout-service
  template:
    metadata:
      labels:
        app: payout-service
    spec:
      containers:
      - name: payout-service
        image: your-registry/payout-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-credentials
              key: secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-credentials
              key: webhook-secret
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payout-service
  namespace: api-direct
spec:
  selector:
    app: payout-service
  ports:
  - port: 8086
    targetPort: 8086
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payout-service-hpa
  namespace: api-direct
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payout-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
