apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  namespace: api-direct
data:
  PORT: "8080"
  AWS_REGION: "us-east-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: api-direct
  labels:
    app: storage-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
        component: backend
    spec:
      serviceAccountName: storage-service
      containers:
      - name: storage
        image: ${ECR_REGISTRY}/api-direct/storage-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: PORT
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: AWS_REGION
        - name: CODE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: platform-secrets
              key: code-storage-bucket
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: api-direct
  labels:
    app: storage-service
spec:
  type: ClusterIP
  selector:
    app: storage-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-service
  namespace: api-direct
  annotations:
    eks.amazonaws.com/role-arn: ${STORAGE_SERVICE_ROLE_ARN}
