name: Deploy API on Release

on:
  release:
    types: [published]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to API-Direct Production
        uses: api-direct/deploy-action@v1
        with:
          api-key: ${{ secrets.API_DIRECT_TOKEN }}
          publish: true
          description: "Production release ${{ github.event.release.tag_name }}"
          category: "Production APIs"
          tags: "production,stable,v${{ github.event.release.tag_name }}"

      - name: Update release with deployment info
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });
            
            const apiUrl = '${{ steps.deploy.outputs.api-url }}';
            const marketplaceUrl = '${{ steps.deploy.outputs.marketplace-url }}';
            
            const updatedBody = release.body + `
            
            ## 🚀 Deployment Information
            
            - **API URL:** [${apiUrl}](${apiUrl})
            - **Marketplace:** [View in Marketplace](${marketplaceUrl})
            - **Health Check:** [${apiUrl}/health](${apiUrl}/health)
            `;
            
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: updatedBody
            });
